"""add_multi_tenancy_workspaces

Revision ID: 0625c5fbfd27
Revises: 2f419d715141
Create Date: 2025-12-31 02:06:26.325213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0625c5fbfd27'
down_revision: Union[str, Sequence[str], None] = '2f419d715141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public.reporting_consolidated')
    op.add_column('alert_configs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('alert_configs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_alert_configs_user_id'), table_name='alert_configs')
    op.drop_constraint(op.f('alert_configs_user_id_fkey'), 'alert_configs', type_='foreignkey')
    op.create_foreign_key(None, 'alert_configs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alert_configs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('alerts', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('alerts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_constraint(op.f('alerts_user_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('api_keys', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'api_keys', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('asset_schema_versions', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset_schema_versions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('assets', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('connections', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('connections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_constraint(op.f('connections_user_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('environments', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'environments', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('job_logs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('jobs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_edges', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline_edges', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_nodes', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline_nodes', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_run_context', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline_run_context', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_runs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('pipeline_runs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_pipeline_runs_user_id'), table_name='pipeline_runs')
    op.drop_constraint(op.f('pipeline_runs_user_id_fkey'), 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_runs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pipeline_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_versions', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline_versions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipelines', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('pipelines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_pipelines_user_id'), table_name='pipelines')
    op.drop_constraint(op.f('pipelines_user_id_fkey'), 'pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'pipelines', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipelines', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('query_history', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query_history', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('scheduler_events', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduler_events', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('step_logs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('step_runs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('active_workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    op.add_column('watermarks', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watermarks', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watermarks', type_='foreignkey')
    op.drop_column('watermarks', 'workspace_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_workspace_id')
    op.drop_constraint(None, 'step_runs', type_='foreignkey')
    op.drop_column('step_runs', 'workspace_id')
    op.drop_constraint(None, 'step_logs', type_='foreignkey')
    op.drop_column('step_logs', 'workspace_id')
    op.drop_constraint(None, 'scheduler_events', type_='foreignkey')
    op.drop_column('scheduler_events', 'workspace_id')
    op.drop_constraint(None, 'query_history', type_='foreignkey')
    op.drop_column('query_history', 'workspace_id')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.create_foreign_key(op.f('pipelines_user_id_fkey'), 'pipelines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pipelines_user_id'), 'pipelines', ['user_id'], unique=False)
    op.alter_column('pipelines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pipelines', 'workspace_id')
    op.drop_constraint(None, 'pipeline_versions', type_='foreignkey')
    op.drop_column('pipeline_versions', 'workspace_id')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_runs_user_id_fkey'), 'pipeline_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pipeline_runs_user_id'), 'pipeline_runs', ['user_id'], unique=False)
    op.alter_column('pipeline_runs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pipeline_runs', 'workspace_id')
    op.drop_constraint(None, 'pipeline_run_context', type_='foreignkey')
    op.drop_column('pipeline_run_context', 'workspace_id')
    op.drop_constraint(None, 'pipeline_nodes', type_='foreignkey')
    op.drop_column('pipeline_nodes', 'workspace_id')
    op.drop_constraint(None, 'pipeline_edges', type_='foreignkey')
    op.drop_column('pipeline_edges', 'workspace_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jobs', 'workspace_id')
    op.drop_constraint(None, 'job_logs', type_='foreignkey')
    op.drop_column('job_logs', 'workspace_id')
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_column('environments', 'workspace_id')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_user_id_fkey'), 'connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.alter_column('connections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('connections', 'workspace_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'workspace_id')
    op.drop_constraint(None, 'asset_schema_versions', type_='foreignkey')
    op.drop_column('asset_schema_versions', 'workspace_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'workspace_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_user_id_fkey'), 'alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alerts', 'workspace_id')
    op.drop_constraint(None, 'alert_configs', type_='foreignkey')
    op.drop_constraint(None, 'alert_configs', type_='foreignkey')
    op.create_foreign_key(op.f('alert_configs_user_id_fkey'), 'alert_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_alert_configs_user_id'), 'alert_configs', ['user_id'], unique=False)
    op.alter_column('alert_configs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alert_configs', 'workspace_id')
    op.create_table('public.reporting_consolidated',
    sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('postId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
