"""Add uppercase OSDU and PROSOURCE to ConnectorType

Revision ID: 246a6bd2d947
Revises: d0ad83c148b2
Create Date: 2026-01-17 21:06:28.864156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246a6bd2d947'
down_revision: Union[str, Sequence[str], None] = 'd0ad83c148b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE connectortype ADD VALUE IF NOT EXISTS 'OSDU'")
        op.execute("ALTER TYPE connectortype ADD VALUE IF NOT EXISTS 'PROSOURCE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
