"""rename_runner_group_to_agent_group

Revision ID: 4003504cb340
Revises: 68a6446e85b2
Create Date: 2026-01-03 00:16:31.119562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4003504cb340'
down_revision: Union[str, Sequence[str], None] = '68a6446e85b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('agent_group', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_pipelines_runner_group'), table_name='pipelines')
    op.create_index(op.f('ix_pipelines_agent_group'), 'pipelines', ['agent_group'], unique=False)
    op.drop_column('pipelines', 'runner_group')
    op.add_column('workspaces', sa.Column('default_agent_group', sa.String(), nullable=True, comment='Default agent tag for all jobs in this workspace'))
    op.drop_column('workspaces', 'default_runner_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('default_runner_group', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Default agent tag for all jobs in this workspace'))
    op.drop_column('workspaces', 'default_agent_group')
    op.add_column('pipelines', sa.Column('runner_group', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pipelines_agent_group'), table_name='pipelines')
    op.create_index(op.f('ix_pipelines_runner_group'), 'pipelines', ['runner_group'], unique=False)
    op.drop_column('pipelines', 'agent_group')
    # ### end Alembic commands ###
