"""add cdc support to pipeline nodes

Revision ID: 4917434e378b
Revises: 6a8b2c3d4e5f
Create Date: 2026-01-14 16:32:09.410982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4917434e378b'
down_revision: Union[str, Sequence[str], None] = '6a8b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_nodes', sa.Column('cdc_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_nodes', 'cdc_config')
    # ### end Alembic commands ###
