"""add_sync_mode_and_quality_profile

Revision ID: 597465b74db5
Revises: ada1ce8ad284
Create Date: 2026-01-14 01:43:05.345745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "597465b74db5"
down_revision: str | Sequence[str] | None = "ada1ce8ad284"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 0. Clean up existing incorrect Enum types if they exist (handling potential case mismatch)  # noqa: E501
    # We use lowercase for all values to match synqx_core.models.enums
    op.execute("DROP TYPE IF EXISTS syncmode CASCADE")
    op.execute("DROP TYPE IF EXISTS writestrategy CASCADE")
    op.execute("DROP TYPE IF EXISTS schemaevolutionpolicy CASCADE")

    # Create the enum types correctly in lowercase
    sync_mode_enum = sa.Enum("full_load", "incremental", "cdc", name="syncmode")
    write_strategy_enum = sa.Enum(
        "append", "overwrite", "upsert", "scd2", name="writestrategy"
    )
    schema_evolution_policy_enum = sa.Enum(
        "strict", "evolve", "ignore", name="schemaevolutionpolicy"
    )

    # Create types in DB explicitly
    sync_mode_enum.create(op.get_bind())
    write_strategy_enum.create(op.get_bind())
    schema_evolution_policy_enum.create(op.get_bind())

    # 1. Add sync_mode
    op.add_column(
        "pipeline_nodes",
        sa.Column(
            "sync_mode", sync_mode_enum, nullable=False, server_default="full_load"
        ),
    )

    # 2. Alter write_strategy
    op.execute("ALTER TABLE pipeline_nodes ALTER COLUMN write_strategy DROP DEFAULT")
    op.alter_column(
        "pipeline_nodes",
        "write_strategy",
        existing_type=sa.VARCHAR(length=50),
        type_=write_strategy_enum,
        existing_nullable=False,
        postgresql_using="write_strategy::writestrategy",
    )
    op.execute(
        "ALTER TABLE pipeline_nodes ALTER COLUMN write_strategy SET DEFAULT 'append'"
    )

    # 3. Alter schema_evolution_policy
    op.execute(
        "ALTER TABLE pipeline_nodes ALTER COLUMN schema_evolution_policy DROP DEFAULT"
    )
    op.alter_column(
        "pipeline_nodes",
        "schema_evolution_policy",
        existing_type=sa.VARCHAR(length=50),
        type_=schema_evolution_policy_enum,
        existing_nullable=False,
        postgresql_using="schema_evolution_policy::schemaevolutionpolicy",
    )
    op.execute(
        "ALTER TABLE pipeline_nodes ALTER COLUMN schema_evolution_policy SET DEFAULT 'strict'"  # noqa: E501
    )

    # 4. Other changes
    op.create_foreign_key(
        None,
        "pipelines",
        "pipeline_versions",
        ["published_version_id"],
        ["id"],
        use_alter=True,
    )
    op.add_column("step_runs", sa.Column("quality_profile", sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("step_runs", "quality_profile")
    op.drop_constraint(None, "pipelines", type_="foreignkey")
    op.alter_column(
        "pipeline_nodes",
        "schema_evolution_policy",
        existing_type=sa.Enum(
            "strict", "evolve", "ignore", name="schemaevolutionpolicy"
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'strict'::character varying"),
    )
    op.alter_column(
        "pipeline_nodes",
        "write_strategy",
        existing_type=sa.Enum(
            "append", "overwrite", "upsert", "scd2", name="writestrategy"
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'append'::character varying"),
    )
    op.drop_column("pipeline_nodes", "sync_mode")
    # ### end Alembic commands ###
