"""add_default_runner_group_to_workspaces

Revision ID: 68a6446e85b2
Revises: ed68220481bc
Create Date: 2026-01-02 23:06:38.830421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a6446e85b2'
down_revision: Union[str, Sequence[str], None] = 'ed68220481bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('default_runner_group', sa.String(), nullable=True, comment='Default agent tag for all jobs in this workspace'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'default_runner_group')
    # ### end Alembic commands ###
