"""add_parent_node_id_for_grouping

Revision ID: b415db031078
Revises: ece86548416a
Create Date: 2026-01-17 17:29:44.192693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b415db031078'
down_revision: Union[str, Sequence[str], None] = 'ece86548416a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_nodes', sa.Column('parent_node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipeline_nodes', 'pipeline_nodes', ['parent_node_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_nodes', type_='foreignkey')
    op.drop_column('pipeline_nodes', 'parent_node_id')
    # ### end Alembic commands ###
