"""remove_parent_node_id_grouping

Revision ID: ce6fae40badb
Revises: b415db031078
Create Date: 2026-01-17 17:52:06.494768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6fae40badb'
down_revision: Union[str, Sequence[str], None] = 'b415db031078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pipeline_nodes_parent_node_id_fkey'), 'pipeline_nodes', type_='foreignkey')
    op.drop_column('pipeline_nodes', 'parent_node_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_nodes', sa.Column('parent_node_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pipeline_nodes_parent_node_id_fkey'), 'pipeline_nodes', 'pipeline_nodes', ['parent_node_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
