"""Add OSDU and ProSource to ConnectorType

Revision ID: d0ad83c148b2
Revises: ce6fae40badb
Create Date: 2026-01-17 19:40:22.704898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad83c148b2'
down_revision: Union[str, Sequence[str], None] = 'ce6fae40badb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE connectortype ADD VALUE IF NOT EXISTS 'osdu'")
        op.execute("ALTER TYPE connectortype ADD VALUE IF NOT EXISTS 'prosource'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
