"""add_advanced_orchestration_and_fanout_support

Revision ID: ece86548416a
Revises: 4917434e378b
Create Date: 2026-01-16 23:23:41.579574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ece86548416a"
down_revision: str | Sequence[str] | None = "4917434e378b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operatortype ADD VALUE 'sub_pipeline'")
    op.execute("ALTER TYPE operatortype ADD VALUE 'switch'")
    op.drop_table("cdc_test_source")
    op.add_column(
        "pipeline_edges", sa.Column("condition", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "pipeline_nodes",
        sa.Column("is_dynamic", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "pipeline_nodes",
        sa.Column("mapping_expr", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "pipeline_nodes", sa.Column("sub_pipeline_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "pipeline_nodes", sa.Column("worker_tag", sa.String(length=100), nullable=True)
    )
    op.create_foreign_key(
        None,
        "pipeline_nodes",
        "pipelines",
        ["sub_pipeline_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pipeline_nodes", type_="foreignkey")
    op.drop_column("pipeline_nodes", "worker_tag")
    op.drop_column("pipeline_nodes", "sub_pipeline_id")
    op.drop_column("pipeline_nodes", "mapping_expr")
    op.drop_column("pipeline_nodes", "is_dynamic")
    op.drop_column("pipeline_edges", "condition")
    op.create_table(
        "cdc_test_source",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cdc_test_source_pkey")),
    )
    # ### end Alembic commands ###
