"""add_runner_secret_hash

Revision ID: ed68220481bc
Revises: f6391ce6ac7e
Create Date: 2026-01-02 12:05:55.690128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed68220481bc'
down_revision: Union[str, Sequence[str], None] = 'f6391ce6ac7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runners', sa.Column('secret_key_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runners', 'secret_key_hash')
    # ### end Alembic commands ###
