"""add_runners_table

Revision ID: f6391ce6ac7e
Revises: fe65b948b53d
Create Date: 2026-01-02 11:40:51.098482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6391ce6ac7e'
down_revision: Union[str, Sequence[str], None] = 'fe65b948b53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('runner_group', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_pipelines_runner_group'), 'pipelines', ['runner_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelines_runner_group'), table_name='pipelines')
    op.drop_column('pipelines', 'runner_group')
    # ### end Alembic commands ###
