"""add_audit_logs_table

Revision ID: fe65b948b53d
Revises: 0625c5fbfd27
Create Date: 2025-12-31 16:11:57.319611

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fe65b948b53d'
down_revision: Union[str, Sequence[str], None] = '0625c5fbfd27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
